### PR TITLE
New TauTagAndProbe code

### PR DESCRIPTION
**Pull request by kandrosov**
New implementation of tag-and-probe tools. 
- redesigned root-tuple;
- the common code base to produce root-tuples for all 3 years;
- multiple tag tau selection methods can be stored in the same tuple. Selection modes include gen-based, pt-based, MVA-based, DeepTau-based;
- introduced pure gen production mode that allows to tag-and-probe root-tuple without dependency on the reconstruction;
- improved gen matching algorithm;
- implemented all latest POG recommendations for electrons, b tag, MET and MET filters;
- simplified tasks submission on CRAB using crab_submit.py and crab_cmd.py;
- cleaned up old code (it is still accessible in the branch "legacy");
- updated instructions (to be improved in the near future).

### CODE REVIEW

**Comment by mbluj** [comment]
Hi, thank you for this development. It is a big set of changes, so it will take some time to revise it - I schedule it later in this week. 
It will be good to get a confirmation that the updated code reproduce results of the old one (or changes are as expected) - I assume it is expected from @hsert?

**Comment by hsert** [comment]
> Hi, thank you for this development. It is a big set of changes, so it will take some time to revise it - I schedule it later in this week.
> It will be good to get a confirmation that the updated code reproduce results of the old one (or changes are as expected) - I assume it is expected from @hsert?

A review from my side and also checking the reproducibility of the previous results will take some time for me too, either end of this week or next week.

**Comment by hsert** [comment]
The comparison plots of the updated code with the previous one can be found in the attached plots for mutau and ditau triggers using 2017_v2 tau MVA tight WP. Slight changes are expected due to following differences:

**Electron ID** is updated to use the recent recommendation as in [https://twiki.cern.ch/twiki/bin/view/CMS/EgammaMiniAODV2](https://twiki.cern.ch/twiki/bin/view/CMS/EgammaMiniAODV2)
- **Old:** mvaElectronID_Fall17_iso_V2_cff
- **New:** 2016-Legacy, 2017-Nov17ReReco, 2018-Prompt

**MET Filters** are added based on [https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2](https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2)
- **Old:** no MET filter were applied
- **New:** MET filters are added

effiComparison_ditau_TightWP2017v2_tightAntiMuIso
effiComparison_mutau_TightWP2017v2_tightAntiMuIso

**Comment by mbluj** [comment]
Thanks for the plots. Efficiency of tau leg of both e+tau and mu+tau triggers with the new code is quite consistently lower by ~2%  than with the old code. Do you understand the difference? 
I do not expect that it can be due to electron ID as selection of tag should not change efficiency of probe i.e. tau, and as electron ID does not matter for mu+tau. So if it is not the code itself which changes results this must be MET filters (however I have not clear idea why it could be possible.) Could you run the new code w/o MET filters to have non-biased comparison?

**Comment by kandrosov** [comment]
> electron ID does not matter for mu+tau

we veto events, with extra electron https://github.com/kandrosov/TauTriggerTools/blob/new-tuple/TauTagAndProbe/plugins/SelectionFilter.cc#L108-L118 So it will have some indirect effect on the mu-tau tag-and-probe selection. But I agree that the effect should be very small.

**Comment by mbluj** [comment]
It looks that this PR is pending since a while... Questions are:
* Do you understand differences wrt previous version and find them acceptable (see discussion above)?
* Does recent set of commits change behaviour of SFs or it is just a set of technical fixes and addons like additional tools?

**Comment by kandrosov** [comment]
> * Do you understand differences wrt previous version and find them acceptable (see discussion above)?

The differences do not seem to be critical, therefore we decided to move ahead and provide the first version of scale factors. However, we plan to investigate it a bit more (after the holidays) before closing this PR.

> * Does recent set of commits change behaviour of SFs or it is just a set of technical fixes and addons like additional tools?

The original PR didn't contain the set of tools to derive the scale factors, but only the root-tuple production part. The recent set of commits slightly changes the root-tuple structure (to extend a wider range of study use-cases) and introduces all the tools that are necessary to produce the final fitted SFs that are delivered in https://github.com/cms-tau-pog/TauTriggerSFs/pull/11.

**Comment by mbluj** [comment]
Thanks for explanations. I keep the PR open until the checks are concluded.

**Comment by kandrosov** [comment]
While there were no further checks for old vs new setup, the new setup was used to derive pre-UL and UL scale factors and these SF were used in multiple analyses. So far, we don't have any reports about possible biases.

In order to move on with the new development, if there are no objections, I'm going to merge this PR.

**Pull request merged**
